version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - monitoring-network
    volumes:
      - prometheus-data:/prometheus
      - prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==wsasus
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    networks:
      - monitoring-network
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==wsasus
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter:latest
    networks:
      - monitoring-network
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - monitoring-network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    ports:
      - "8080:8080"

networks:
  monitoring-network:
    external: true

volumes:
  prometheus-data:
  prometheus-config:
  grafana-data:
